# action.yml
name: 'CWTools Action'
description: 'Run CWTools on your HoI4 code'
inputs: 
  game:
    description: 'What game to use. Supported values: hoi4, ck2, eu4, ir, stellaris, vic2.'
    required: true
  cache:
    description: 'Path to the full cache file (cwb.bz2) in $GITHUB_WORKSPACE (root of repository). Use an empty string to use metadata from cwtools/cwtools-cache-files (Default: use metadata)'
    required: false
    default: ''
  rules:
    description: 'What rules repository to use (Default: https://github.com/cwtools/cwtools-$INPUT_GAME-config.git)'
    required: false
    default: '' #if empty, use cwtools/cwtools-$INPUT_GAME-config.git
  rulesRef:
    description: 'What ref on rules repo to checkout (Default: master)'
    required: false
    default: 'master'
  changedFilesOnly:
    description: 'Whether to only push offences in changed files (Default: True, set to 0 for False)'
    required: false
    default: '1'
  suppressedOffenceCategories:
    description: 'What CWTools offence categories to suppress, in JSON format: {"failure":[], "warning":[], "notice":[]}'
    required: false
    default: '{"failure":[], "warning":[], "notice":[]}'
runs:
  using: 'docker'
  image: 'Dockerfile'