# action.yml
name: 'CWTools Action'
description: 'Run CWTools on your Clausewitz mod PDXScript code in parallel to your builds'
branding:
  icon: 'check'  
  color: 'purple'
inputs: 
  game:
    description: 'What game to use. Supported values: hoi4, ck2, eu4, ir, stellaris, vic2.'
    required: true
  modPath:
    description: 'Path to the mod folder in $GITHUB_WORKSPACE (root of repository). (Default: "" - root of repository itself)'
    required: false
    default: ''
  cache:
    description: 'Path to the full cache file (cwb.bz2) in $GITHUB_WORKSPACE (root of repository). Use an empty string to use metadata from cwtools/cwtools-cache-files (Default: use metadata)'
    required: false
    default: ''
  vanillaMode:
    description: 'Whether to not use cache, and instead treat the project as a vanilla game installation folder - if you are a modder, you probably should not be using this. If True, cache input will be ignored (Default: False, set to anything other than 0 or blank for True)'
    required: false
    default: '0'
  locLanguages:
    description: 'Which languages to check localisation for, space separated, lowercase (eg. "english spanish russian"). Note: May be different from game to game. (Default: english)'
    required: false
    default: 'english'
  rules:
    description: 'What rules repository to use (Default: https://github.com/cwtools/cwtools-$INPUT_GAME-config.git)'
    required: false
    default: '' #if empty, use cwtools/cwtools-$INPUT_GAME-config.git
  rulesRef:
    description: 'What ref on rules repo to checkout (Default: master)'
    required: false
    default: 'master'
  changedFilesOnly:
    description: 'Whether to only push offences in changed files (Default: True, set to 0 or blank for False)'
    required: false
    default: '1'
  suppressedOffenceCategories:
    description: 'What CWTools offence categories to suppress, in JSON format: {"failure":[], "warning":[], "notice":[]}'
    required: false
    default: '{"failure":[], "warning":[], "notice":[]}'
  suppressedFiles:
    description: 'Which files to completely ignore, in JSON format: ["path/from/root/repo/folder", "path/from/root/repo/folder"]'
    required: false
    default: '[]'
  CWToolsCLIVersion:
    description: 'Which CWTools.CLI version to use (Default: latest stable)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
