# action.yml
name: 'CWTools Action'
description: 'Run CWTools on your HoI4 code'
inputs: 
  game:
    description: 'What game to use. Supported values: hoi4, ck2, eu4, ir, stellaris, vic2.'
    required: true
  changedFilesOnly:
    description: 'Whether to only push offences in changed files (Default: True, set to 0 for False)'
    required: false
    default: '1'
  suppressedOffenceCategories:
    description: 'What CWTools offence categories to suppress, in JSON format: {"failure":[], "warning":[], "notice":[]}'
    required: false
    default: '{"failure":[], "warning":[], "notice":[]}'
runs:
  using: 'docker'
  image: 'Dockerfile'