# action.yml
name: 'CWTools Action'
description: 'Run CWTools on your HoI4 code'
inputs: 
  changedFilesOnly:
    description: 'Whether to only push offences in changed files (Default: True, set to 0 for False)'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'